# Lab | Chains in LangChain

## Outline

* LLMChain
* Sequential Chains
  * SimpleSequentialChain
  * SequentialChain
* Router Chain

In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import os

from dotenv import load_dotenv, find_dotenv
_ = load_dotenv(find_dotenv())

OPENAI_API_KEY  = os.getenv('OPENAI_API_KEY')
HUGGINGFACEHUB_API_TOKEN = os.getenv('HUGGINGFACEHUB_API_TOKEN')

In [3]:
!pip install pandas

Requirement already satisfied: pandas in /Users/basstianlopez/miniconda3/lib/python3.13/site-packages (3.0.3)
Requirement already satisfied: numpy>=1.26.0 in /Users/basstianlopez/miniconda3/lib/python3.13/site-packages (from pandas) (2.3.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/basstianlopez/miniconda3/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/basstianlopez/miniconda3/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [4]:
import pandas as pd
df = pd.read_csv('/Users/basstianlopez/Desktop/it-studies/Curses/ironhack/week_16/day3/labs/lab-chains-in-langchain/data/Data.csv')

In [5]:
df.head()
#df.sample()

                   Product                                             Review
0     Queen Size Sheet Set  I ordered a king size set. My only criticism w...
1   Waterproof Phone Pouch  I loved the waterproof sac, although the openi...
2      Luxury Air Mattress  This mattress had a small hole in the top of i...
3           Pillows Insert  This is the best throw pillow fillers on Amazo...
4  Milk Frother Handheld\n   I loved this product. But they only seem to l...

## LLMChain

In [6]:
!pip install langchain_community

Requirement already satisfied: langchain_community in /Users/basstianlopez/miniconda3/lib/python3.13/site-packages (0.4.1)
Requirement already satisfied: langchain-core<2.0.0,>=1.0.1 in /Users/basstianlopez/miniconda3/lib/python3.13/site-packages (from langchain_community) (1.4.0)
Requirement already satisfied: langchain-classic<2.0.0,>=1.0.0 in /Users/basstianlopez/miniconda3/lib/python3.13/site-packages (from langchain_community) (1.0.7)
Requirement already satisfied: SQLAlchemy<3.0.0,>=1.4.0 in /Users/basstianlopez/miniconda3/lib/python3.13/site-packages (from langchain_community) (2.0.49)
Requirement already satisfied: requests<3.0.0,>=2.32.5 in /Users/basstianlopez/miniconda3/lib/python3.13/site-packages (from langchain_community) (2.32.5)
Requirement already satisfied: PyYAML<7.0.0,>=5.3.0 in /Users/basstianlopez/miniconda3/lib/python3.13/site-packages (from langchain_community) (6.0.3)
Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in /Users/basstianlopez/miniconda3/lib/python3.13/site-packages (from langchain_community) (3.13.5)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /Users/basstianlopez/miniconda3/lib/python3.13/site-packages (from langchain_community) (9.1.4)
Requirement already satisfied: dataclasses-json<0.7.0,>=0.6.7 in /Users/basstianlopez/miniconda3/lib/python3.13/site-packages (from langchain_community) (0.6.7)
Requirement already satisfied: pydantic-settings<3.0.0,>=2.10.1 in /Users/basstianlopez/miniconda3/lib/python3.13/site-packages (from langchain_community) (2.14.1)
Requirement already satisfied: langsmith<1.0.0,>=0.1.125 in /Users/basstianlopez/miniconda3/lib/python3.13/site-packages (from langchain_community) (0.8.5)
Requirement already satisfied: httpx-sse<1.0.0,>=0.4.0 in /Users/basstianlopez/miniconda3/lib/python3.13/site-packages (from langchain_community) (0.4.3)
Requirement already satisfied: numpy>=2.1.0 in /Users/basstianlopez/miniconda3/lib/python3.13/site-packages (from langchain_community) (2.3.1)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /Users/basstianlopez/miniconda3/lib/python3.13/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /Users/basstianlopez/miniconda3/lib/python3.13/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /Users/basstianlopez/miniconda3/lib/python3.13/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /Users/basstianlopez/miniconda3/lib/python3.13/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /Users/basstianlopez/miniconda3/lib/python3.13/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /Users/basstianlopez/miniconda3/lib/python3.13/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /Users/basstianlopez/miniconda3/lib/python3.13/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (1.23.0)
Requirement already satisfied: marshmallow<4.0.0,>=3.18.0 in /Users/basstianlopez/miniconda3/lib/python3.13/site-packages (from dataclasses-json<0.7.0,>=0.6.7->langchain_community) (3.26.2)
Requirement already satisfied: typing-inspect<1,>=0.4.0 in /Users/basstianlopez/miniconda3/lib/python3.13/site-packages (from dataclasses-json<0.7.0,>=0.6.7->langchain_community) (0.9.0)
Requirement already satisfied: langchain-text-splitters<2.0.0,>=1.1.2 in /Users/basstianlopez/miniconda3/lib/python3.13/site-packages (from langchain-classic<2.0.0,>=1.0.0->langchain_community) (1.1.2)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /Users/basstianlopez/miniconda3/lib/python3.13/site-packages (from langchain-classic<2.0.0,>=1.0.0->langchain_community) (2.11.7)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /Users/basstianlopez/miniconda3/lib/python3.13/site-packages (from langchain-core<2.0.0,>=1.0.1->langchain_community) (1.33)
Requirement already satisfied: langchain-protocol>=0.0.14 in /Users/basstianlopez/miniconda3/lib/python3.13/site-packages (from langchain-core<2.0.0,>=1.0.1->langchain_community) (0.0.15)
Requirement already satisfied: packaging>=23.2.0 in /Users/basstianlopez/miniconda3/lib/python3.13/site-packages (from langchain-core<2.0.0,>=1.0.1->langchain_community) (25.0)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in /Users/basstianlopez/miniconda3/lib/python3.13/site-packages (from langchain-core<2.0.0,>=1.0.1->langchain_community) (4.12.2)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /Users/basstianlopez/miniconda3/lib/python3.13/site-packages (from langchain-core<2.0.0,>=1.0.1->langchain_community) (0.15.0)
Requirement already satisfied: jsonpointer>=1.9 in /Users/basstianlopez/miniconda3/lib/python3.13/site-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.0.1->langchain_community) (3.0.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /Users/basstianlopez/miniconda3/lib/python3.13/site-packages (from langsmith<1.0.0,>=0.1.125->langchain_community) (0.28.1)
Requirement already satisfied: orjson>=3.9.14 in /Users/basstianlopez/miniconda3/lib/python3.13/site-packages (from langsmith<1.0.0,>=0.1.125->langchain_community) (3.11.9)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /Users/basstianlopez/miniconda3/lib/python3.13/site-packages (from langsmith<1.0.0,>=0.1.125->langchain_community) (1.0.0)
Requirement already satisfied: xxhash>=3.0.0 in /Users/basstianlopez/miniconda3/lib/python3.13/site-packages (from langsmith<1.0.0,>=0.1.125->langchain_community) (3.7.0)
Requirement already satisfied: zstandard>=0.23.0 in /Users/basstianlopez/miniconda3/lib/python3.13/site-packages (from langsmith<1.0.0,>=0.1.125->langchain_community) (0.23.0)
Requirement already satisfied: anyio in /Users/basstianlopez/miniconda3/lib/python3.13/site-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain_community) (4.12.1)
Requirement already satisfied: certifi in /Users/basstianlopez/miniconda3/lib/python3.13/site-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain_community) (2026.1.4)
Requirement already satisfied: httpcore==1.* in /Users/basstianlopez/miniconda3/lib/python3.13/site-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain_community) (1.0.9)
Requirement already satisfied: idna in /Users/basstianlopez/miniconda3/lib/python3.13/site-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain_community) (3.7)
Requirement already satisfied: h11>=0.16 in /Users/basstianlopez/miniconda3/lib/python3.13/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain_community) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in /Users/basstianlopez/miniconda3/lib/python3.13/site-packages (from pydantic<3.0.0,>=2.7.4->langchain-classic<2.0.0,>=1.0.0->langchain_community) (0.6.0)
Requirement already satisfied: pydantic-core==2.33.2 in /Users/basstianlopez/miniconda3/lib/python3.13/site-packages (from pydantic<3.0.0,>=2.7.4->langchain-classic<2.0.0,>=1.0.0->langchain_community) (2.33.2)
Requirement already satisfied: typing-inspection>=0.4.0 in /Users/basstianlopez/miniconda3/lib/python3.13/site-packages (from pydantic<3.0.0,>=2.7.4->langchain-classic<2.0.0,>=1.0.0->langchain_community) (0.4.0)
Requirement already satisfied: python-dotenv>=0.21.0 in /Users/basstianlopez/miniconda3/lib/python3.13/site-packages (from pydantic-settings<3.0.0,>=2.10.1->langchain_community) (1.1.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/basstianlopez/miniconda3/lib/python3.13/site-packages (from requests<3.0.0,>=2.32.5->langchain_community) (3.3.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/basstianlopez/miniconda3/lib/python3.13/site-packages (from requests<3.0.0,>=2.32.5->langchain_community) (2.5.0)
Requirement already satisfied: greenlet>=1 in /Users/basstianlopez/miniconda3/lib/python3.13/site-packages (from SQLAlchemy<3.0.0,>=1.4.0->langchain_community) (3.5.0)
Requirement already satisfied: mypy-extensions>=0.3.0 in /Users/basstianlopez/miniconda3/lib/python3.13/site-packages (from typing-inspect<1,>=0.4.0->dataclasses-json<0.7.0,>=0.6.7->langchain_community) (1.1.0)

In [7]:
from langchain_openai import ChatOpenAI
from langchain.prompts import ChatPromptTemplate
#from langchain_core.prompts import ChatPromptTemplate
from langchain.chains import LLMChain
#from langchain_community.chains import LLMChain

In [11]:
#Replace None by your own value and justify
llm = ChatOpenAI(temperature=0)

#At a low temperature (0), the model almost always chooses the single most predictable next word, generating very consistent and factual results. 
#As you turn the dial up, the model is more likely to consider less obvious word choices, leading to more varied and creative, but less predictable, outputs

In [16]:
prompt = ChatPromptTemplate.from_template("Describe the product: {product}"
)
#Write a query that would take a variable to describe any product

In [17]:

chain = LLMChain(llm=llm, prompt=prompt)

In [18]:
product = "Queen Size Sheet Set" #Select a product type to be describe
chain.run(product)

'The Queen Size Sheet Set is a bedding product that includes a fitted sheet, flat sheet, and two pillowcases designed to fit a queen size mattress. The sheets are typically made from soft and comfortable materials such as cotton, microfiber, or bamboo, and come in a variety of colors and patterns to suit different bedroom decor styles. The fitted sheet has elasticized edges to ensure a snug fit on the mattress, while the flat sheet provides a smooth and cozy layer to sleep on. The pillowcases are designed to fit standard queen size pillows. This sheet set is a convenient and stylish way to dress up your bed and create a comfortable sleeping environment.'

## SimpleSequentialChain

In [19]:
from langchain.chains import SimpleSequentialChain

In [26]:
llm = ChatOpenAI(temperature=0.9)

# prompt template 1
first_prompt = ChatPromptTemplate.from_template("When you can use this the {product}"
    #Repeat the initial query or create a new query that would feed into the second prompt
)

# Chain 1
chain_one = LLMChain(llm=llm, prompt=first_prompt)

In [30]:

# prompt template 2
second_prompt = ChatPromptTemplate.from_template("What people say of give other uses different as {when}"
    #Write the second prompt query that takes an input variable whose input will come from the previous prompt"
)
# chain 2
chain_two = LLMChain(llm=llm, prompt=second_prompt)

In [31]:
overall_simple_chain = SimpleSequentialChain(chains=[chain_one, chain_two],verbose=True)

In [32]:
overall_simple_chain.run(product)

Error in StdOutCallbackHandler.on_chain_start callback: AttributeError("'NoneType' object has no attribute 'get'")

You can use a Queen Size Sheet Set on a Queen size bed. It includes a fitted sheet, a flat sheet, and two pillowcases. It is typically used to cover and protect the mattress and pillows on a Queen size bed.
However, some creative uses for a Queen Size Sheet Set include:

1. DIY curtains: Use the flat sheet to create curtains for your windows. Simply hem the edges and attach curtain rings or hooks for easy hanging.

2. Tablecloth: Use the flat sheet as a tablecloth for a large dining table or outdoor picnic. It can easily be washed and reused for future gatherings.

3. DIY bedding for pets: Cut up the fitted sheet and pillowcases to create cozy bedding for your pets. They will love snuggling up on the soft fabric.

4. Crafting projects: Use the sheets for various crafting projects, such as making pillow covers, tote bags, or even clothing items like skirts or dresses.

5. Outdoor blanket: Use the flat sheet as a picnic blanket for outdoor outings. It provides a comfortable and easy-to-clean surface for lounging in the park or at the beach.

Overall, a Queen Size Sheet Set can be repurposed in many creative ways beyond its traditional use on a bed. Let your imagination run wild and find new ways to utilize this versatile item in your home.

> Finished chain.

'However, some creative uses for a Queen Size Sheet Set include:\n\n1. DIY curtains: Use the flat sheet to create curtains for your windows. Simply hem the edges and attach curtain rings or hooks for easy hanging.\n\n2. Tablecloth: Use the flat sheet as a tablecloth for a large dining table or outdoor picnic. It can easily be washed and reused for future gatherings.\n\n3. DIY bedding for pets: Cut up the fitted sheet and pillowcases to create cozy bedding for your pets. They will love snuggling up on the soft fabric.\n\n4. Crafting projects: Use the sheets for various crafting projects, such as making pillow covers, tote bags, or even clothing items like skirts or dresses.\n\n5. Outdoor blanket: Use the flat sheet as a picnic blanket for outdoor outings. It provides a comfortable and easy-to-clean surface for lounging in the park or at the beach.\n\nOverall, a Queen Size Sheet Set can be repurposed in many creative ways beyond its traditional use on a bed. Let your imagination run wild and find new ways to utilize this versatile item in your home.'

**Repeat the above twice for different products**

In [35]:



product = "Luxury Air Mattress"
chain.run(product)

from langchain.chains import SimpleSequentialChain
llm = ChatOpenAI(temperature=0.9)
# prompt template 1
first_prompt = ChatPromptTemplate.from_template("How many years can i use {product}"
    #Repeat the initial query or create a new query that would feed into the second prompt
)
# Chain 1
chain_one = LLMChain(llm=llm, prompt=first_prompt) 
# prompt template 2
second_prompt = ChatPromptTemplate.from_template("After {years} when can i reciclying it"
    #Write the second prompt query that takes an input variable whose input will come from the previous prompt"
)
# chain 2
chain_two = LLMChain(llm=llm, prompt=second_prompt) 
overall_simple_chain = SimpleSequentialChain(chains=[chain_one, chain_two],verbose=True)
overall_simple_chain.run(product)

Error in StdOutCallbackHandler.on_chain_start callback: AttributeError("'NoneType' object has no attribute 'get'")

The lifespan of a luxury air mattress can vary depending on the quality of the product and how well it is cared for. On average, a high-quality luxury air mattress can last anywhere from 5 to 10 years with proper maintenance and regular use. It is important to follow the manufacturer's guidelines for care and maintenance to ensure the longevity of your air mattress.
When it comes time to recycle your luxury air mattress, you should first check with your local waste management facility to see if they accept air mattresses for recycling. Some facilities may have specific procedures for recycling mattresses, so it's important to follow their guidelines.

If your local facility does not accept air mattresses for recycling, you can also check with mattress recycling companies in your area. These companies specialize in recycling mattresses and may be able to take your air mattress off your hands.

If neither of these options are available to you, you can also consider donating your air mattress to a charity or thrift store, as long as it is still in good condition. This way, someone else may be able to benefit from the mattress even if you no longer need it.

> Finished chain.

"When it comes time to recycle your luxury air mattress, you should first check with your local waste management facility to see if they accept air mattresses for recycling. Some facilities may have specific procedures for recycling mattresses, so it's important to follow their guidelines.\n\nIf your local facility does not accept air mattresses for recycling, you can also check with mattress recycling companies in your area. These companies specialize in recycling mattresses and may be able to take your air mattress off your hands.\n\nIf neither of these options are available to you, you can also consider donating your air mattress to a charity or thrift store, as long as it is still in good condition. This way, someone else may be able to benefit from the mattress even if you no longer need it."

In [37]:
df.head()

                   Product                                             Review
0     Queen Size Sheet Set  I ordered a king size set. My only criticism w...
1   Waterproof Phone Pouch  I loved the waterproof sac, although the openi...
2      Luxury Air Mattress  This mattress had a small hole in the top of i...
3           Pillows Insert  This is the best throw pillow fillers on Amazo...
4  Milk Frother Handheld\n   I loved this product. But they only seem to l...

In [38]:

product = "Milk Frother Handheld\n"
chain.run(product)

from langchain.chains import SimpleSequentialChain
llm = ChatOpenAI(temperature=0.9)
# prompt template 1
first_prompt = ChatPromptTemplate.from_template("do the people love is this {product}?"
    #Repeat the initial query or create a new query that would feed into the second prompt
)
# Chain 1
chain_one = LLMChain(llm=llm, prompt=first_prompt) 
# prompt template 2
second_prompt = ChatPromptTemplate.from_template("What could be my status tu by that {prodcut}"
    #Write the second prompt query that takes an input variable whose input will come from the previous prompt"
)
# chain 2
chain_two = LLMChain(llm=llm, prompt=second_prompt) 
overall_simple_chain = SimpleSequentialChain(chains=[chain_one, chain_two],verbose=True)
overall_simple_chain.run(product)

Error in StdOutCallbackHandler.on_chain_start callback: AttributeError("'NoneType' object has no attribute 'get'")

It ultimately depends on the individual's preferences and needs. Some people may love a handheld milk frother for its convenience and ease of use, while others may prefer a different method for frothing milk. It's best to read reviews and do research to see if a handheld milk frother is the right fit for you.
Ultimately, you should consider your own needs and preferences when determining whether a handheld milk frother is the right choice for you. Some factors to consider include how often you will be using it, your budget, and your space limitations. Researching different options and reading reviews can help you make an informed decision.

> Finished chain.

'Ultimately, you should consider your own needs and preferences when determining whether a handheld milk frother is the right choice for you. Some factors to consider include how often you will be using it, your budget, and your space limitations. Researching different options and reading reviews can help you make an informed decision.'

## SequentialChain

In [39]:
from langchain.chains import SequentialChain

In [78]:
llm = ChatOpenAI(temperature=0.9)


first_prompt = ChatPromptTemplate.from_template("Translate the following product review to Spanish. Return ONLY the translation, no explanations:\n\n{Review}"
  #This prompt should translate a review
)

chain_one = LLMChain(llm=llm, prompt=first_prompt, 
                     output_key="espaReview" #Give a name to your output
                    )

In [79]:
second_prompt = ChatPromptTemplate.from_template("Summarize this Spanish review in one short sentence:\n{espaReview}"
    #Write a promplt to summarize a review
)

chain_two = LLMChain(llm=llm, prompt=second_prompt, 
                     output_key="sumR1" #give a name to this output
                    )

In [80]:
# prompt template 3: translate to english or other language
third_prompt = ChatPromptTemplate.from_template("Translate this Spanish review to German:\n{espaReview}"
)
# chain 3: input= Review and output= language
chain_three = LLMChain(llm=llm, prompt=third_prompt,
                       output_key="GermanReview"
                      )

In [81]:

# prompt template 4: follow up message that take as inputs the two previous prompts' variables
fourth_prompt = ChatPromptTemplate.from_template("Review in German: {GermanReview}\nSummary in Spanish: {sumR1}\n\nWrite a short analysis comparing these two versions."
)
chain_four = LLMChain(llm=llm, prompt=fourth_prompt,
                      output_key="stepback"
                     )

In [65]:
help(SequentialChain)

Help on class SequentialChain in module langchain.chains.sequential:

class SequentialChain(langchain.chains.base.Chain)
 |  SequentialChain(*args: Any, name: Optional[str] = None, memory: Optional[langchain_core.memory.BaseMemory] = None, callbacks: Union[List[langchain_core.callbacks.base.BaseCallbackHandler], langchain_core.callbacks.base.BaseCallbackManager, NoneType] = None, verbose: bool = None, tags: Optional[List[str]] = None, metadata: Optional[Dict[str, Any]] = None, callback_manager: Optional[langchain_core.callbacks.base.BaseCallbackManager] = None, chains: List[langchain.chains.base.Chain], input_variables: List[str], output_variables: List[str], return_all: bool = False) -> None
 |
 |  Chain where the outputs of one chain feed directly into next.
 |
 |  Method resolution order:
 |      SequentialChain
 |      langchain.chains.base.Chain
 |      langchain_core.runnables.base.RunnableSerializable
 |      langchain_core.load.serializable.Serializable
 |      pydantic.v1.main.BaseModel
 |      pydantic.v1.utils.Representation
 |      langchain_core.runnables.base.Runnable
 |      typing.Generic
 |      abc.ABC
 |      builtins.object
 |
 |  Class methods defined here:
 |
 |  validate_chains(values: Dict) -> Dict
 |      Validate that the correct inputs exist for all chains.
 |
 |  ----------------------------------------------------------------------
 |  Static methods defined here:
 |
 |  __json_encoder__ = pydantic_encoder(obj: Any) -> Any from pydantic.v1.json
 |
 |  ----------------------------------------------------------------------
 |  Readonly properties defined here:
 |
 |  input_keys
 |      Return expected input keys to the chain.
 |
 |      :meta private:
 |
 |  output_keys
 |      Return output key.
 |
 |      :meta private:
 |
 |  ----------------------------------------------------------------------
 |  Data and other attributes defined here:
 |
 |  Config = <class 'langchain.chains.sequential.SequentialChain.Config'>
 |
 |  __abstractmethods__ = frozenset()
 |
 |  __annotations__ = {'chains': typing.List[langchain.chains.base.Chain],...
 |
 |  __class_vars__ = set()
 |
 |  __config__ = <class 'pydantic.v1.config.Config'>
 |
 |  __custom_root_type__ = False
 |
 |  __exclude_fields__ = {'callback_manager': True, 'callbacks': True}
 |
 |  __fields__ = {'callback_manager': ModelField(name='callback_manager', ...
 |
 |  __hash__ = None
 |
 |  __include_fields__ = None
 |
 |  __parameters__ = ()
 |
 |  __post_root_validators__ = []
 |
 |  __pre_root_validators__ = [<function Chain.raise_callback_manager_depr...
 |
 |  __private_attributes__ = {}
 |
 |  __schema_cache__ = {}
 |
 |  __signature__ = <Signature (*args: Any, name: Optional[str] = No...es:...
 |
 |  __validators__ = {'verbose': [<pydantic.v1.class_validators.Validator ...
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from langchain.chains.base.Chain:
 |
 |  __call__(self, inputs: Union[Dict[str, Any], Any], return_only_outputs: bool = False, callbacks: Union[List[langchain_core.callbacks.base.BaseCallbackHandler], langchain_core.callbacks.base.BaseCallbackManager, NoneType] = None, *, tags: Optional[List[str]] = None, metadata: Optional[Dict[str, Any]] = None, run_name: Optional[str] = None, include_run_info: bool = False) -> Dict[str, Any]
 |      .. deprecated:: langchain==0.1.0 Use ``invoke`` instead.
 |
 |      Execute the chain.
 |
 |      Args:
 |          inputs: Dictionary of inputs, or single input if chain expects
 |              only one param. Should contain all inputs specified in
 |              `Chain.input_keys` except for inputs that will be set by the chain's
 |              memory.
 |          return_only_outputs: Whether to return only outputs in the
 |              response. If True, only new keys generated by this chain will be
 |              returned. If False, both input keys and new keys generated by this
 |              chain will be returned. Defaults to False.
 |          callbacks: Callbacks to use for this chain run. These will be called in
 |              addition to callbacks passed to the chain during construction, but only
 |              these runtime callbacks will propagate to calls to other objects.
 |          tags: List of string tags to pass to all callbacks. These will be passed in
 |              addition to tags passed to the chain during construction, but only
 |              these runtime tags will propagate to calls to other objects.
 |          metadata: Optional metadata associated with the chain. Defaults to None
 |          include_run_info: Whether to include run info in the response. Defaults
 |              to False.
 |
 |      Returns:
 |          A dict of named outputs. Should contain all outputs specified in
 |              `Chain.output_keys`.
 |
 |  async acall(self, inputs: Union[Dict[str, Any], Any], return_only_outputs: bool = False, callbacks: Union[List[langchain_core.callbacks.base.BaseCallbackHandler], langchain_core.callbacks.base.BaseCallbackManager, NoneType] = None, *, tags: Optional[List[str]] = None, metadata: Optional[Dict[str, Any]] = None, run_name: Optional[str] = None, include_run_info: bool = False) -> Dict[str, Any]
 |      .. deprecated:: langchain==0.1.0 Use ``ainvoke`` instead.
 |
 |      Asynchronously execute the chain.
 |
 |      Args:
 |          inputs: Dictionary of inputs, or single input if chain expects
 |              only one param. Should contain all inputs specified in
 |              `Chain.input_keys` except for inputs that will be set by the chain's
 |              memory.
 |          return_only_outputs: Whether to return only outputs in the
 |              response. If True, only new keys generated by this chain will be
 |              returned. If False, both input keys and new keys generated by this
 |              chain will be returned. Defaults to False.
 |          callbacks: Callbacks to use for this chain run. These will be called in
 |              addition to callbacks passed to the chain during construction, but only
 |              these runtime callbacks will propagate to calls to other objects.
 |          tags: List of string tags to pass to all callbacks. These will be passed in
 |              addition to tags passed to the chain during construction, but only
 |              these runtime tags will propagate to calls to other objects.
 |          metadata: Optional metadata associated with the chain. Defaults to None
 |          include_run_info: Whether to include run info in the response. Defaults
 |              to False.
 |
 |      Returns:
 |          A dict of named outputs. Should contain all outputs specified in
 |              `Chain.output_keys`.
 |
 |  async ainvoke(self, input: Dict[str, Any], config: Optional[langchain_core.runnables.config.RunnableConfig] = None, **kwargs: Any) -> Dict[str, Any]
 |      Default implementation of ainvoke, calls invoke from a thread.
 |
 |      The default implementation allows usage of async code even if
 |      the Runnable did not implement a native async version of invoke.
 |
 |      Subclasses should override this method if they can run asynchronously.
 |
 |  apply(self, input_list: List[Dict[str, Any]], callbacks: Union[List[langchain_core.callbacks.base.BaseCallbackHandler], langchain_core.callbacks.base.BaseCallbackManager, NoneType] = None) -> List[Dict[str, str]]
 |      .. deprecated:: langchain==0.1.0 Use ``batch`` instead.
 |
 |      Call the chain on all inputs in the list.
 |
 |  async aprep_inputs(self, inputs: Union[Dict[str, Any], Any]) -> Dict[str, str]
 |      Prepare chain inputs, including adding inputs from memory.
 |
 |      Args:
 |          inputs: Dictionary of raw inputs, or single input if chain expects
 |              only one param. Should contain all inputs specified in
 |              `Chain.input_keys` except for inputs that will be set by the chain's
 |              memory.
 |
 |      Returns:
 |          A dictionary of all inputs, including those added by the chain's memory.
 |
 |  async aprep_outputs(self, inputs: Dict[str, str], outputs: Dict[str, str], return_only_outputs: bool = False) -> Dict[str, str]
 |      Validate and prepare chain outputs, and save info about this run to memory.
 |
 |      Args:
 |          inputs: Dictionary of chain inputs, including any inputs added by chain
 |              memory.
 |          outputs: Dictionary of initial chain outputs.
 |          return_only_outputs: Whether to only return the chain outputs. If False,
 |              inputs are also added to the final outputs.
 |
 |      Returns:
 |          A dict of the final chain outputs.
 |
 |  async arun(self, *args: Any, callbacks: Union[List[langchain_core.callbacks.base.BaseCallbackHandler], langchain_core.callbacks.base.BaseCallbackManager, NoneType] = None, tags: Optional[List[str]] = None, metadata: Optional[Dict[str, Any]] = None, **kwargs: Any) -> Any
 |      .. deprecated:: langchain==0.1.0 Use ``ainvoke`` instead.
 |
 |      Convenience method for executing chain.
 |
 |      The main difference between this method and `Chain.__call__` is that this
 |      method expects inputs to be passed directly in as positional arguments or
 |      keyword arguments, whereas `Chain.__call__` expects a single input dictionary
 |      with all the inputs
 |
 |
 |      Args:
 |          *args: If the chain expects a single input, it can be passed in as the
 |              sole positional argument.
 |          callbacks: Callbacks to use for this chain run. These will be called in
 |              addition to callbacks passed to the chain during construction, but only
 |              these runtime callbacks will propagate to calls to other objects.
 |          tags: List of string tags to pass to all callbacks. These will be passed in
 |              addition to tags passed to the chain during construction, but only
 |              these runtime tags will propagate to calls to other objects.
 |          **kwargs: If the chain expects multiple inputs, they can be passed in
 |              directly as keyword arguments.
 |
 |      Returns:
 |          The chain output.
 |
 |      Example:
 |          .. code-block:: python
 |
 |              # Suppose we have a single-input chain that takes a 'question' string:
 |              await chain.arun("What's the temperature in Boise, Idaho?")
 |              # -> "The temperature in Boise is..."
 |
 |              # Suppose we have a multi-input chain that takes a 'question' string
 |              # and 'context' string:
 |              question = "What's the temperature in Boise, Idaho?"
 |              context = "Weather report for Boise, Idaho on 07/03/23..."
 |              await chain.arun(question=question, context=context)
 |              # -> "The temperature in Boise is..."
 |
 |  dict(self, **kwargs: Any) -> Dict
 |      Dictionary representation of chain.
 |
 |      Expects `Chain._chain_type` property to be implemented and for memory to be
 |          null.
 |
 |      Args:
 |          **kwargs: Keyword arguments passed to default `pydantic.BaseModel.dict`
 |              method.
 |
 |      Returns:
 |          A dictionary representation of the chain.
 |
 |      Example:
 |          .. code-block:: python
 |
 |              chain.dict(exclude_unset=True)
 |              # -> {"_type": "foo", "verbose": False, ...}
 |
 |  get_input_schema(self, config: Optional[langchain_core.runnables.config.RunnableConfig] = None) -> Type[pydantic.v1.main.BaseModel]
 |      Get a pydantic model that can be used to validate input to the Runnable.
 |
 |      Runnables that leverage the configurable_fields and configurable_alternatives
 |      methods will have a dynamic input schema that depends on which
 |      configuration the Runnable is invoked with.
 |
 |      This method allows to get an input schema for a specific configuration.
 |
 |      Args:
 |          config: A config to use when generating the schema.
 |
 |      Returns:
 |          A pydantic model that can be used to validate input.
 |
 |  get_output_schema(self, config: Optional[langchain_core.runnables.config.RunnableConfig] = None) -> Type[pydantic.v1.main.BaseModel]
 |      Get a pydantic model that can be used to validate output to the Runnable.
 |
 |      Runnables that leverage the configurable_fields and configurable_alternatives
 |      methods will have a dynamic output schema that depends on which
 |      configuration the Runnable is invoked with.
 |
 |      This method allows to get an output schema for a specific configuration.
 |
 |      Args:
 |          config: A config to use when generating the schema.
 |
 |      Returns:
 |          A pydantic model that can be used to validate output.
 |
 |  invoke(self, input: Dict[str, Any], config: Optional[langchain_core.runnables.config.RunnableConfig] = None, **kwargs: Any) -> Dict[str, Any]
 |      Transform a single input into an output. Override to implement.
 |
 |      Args:
 |          input: The input to the Runnable.
 |          config: A config to use when invoking the Runnable.
 |             The config supports standard keys like 'tags', 'metadata' for tracing
 |             purposes, 'max_concurrency' for controlling how much work to do
 |             in parallel, and other keys. Please refer to the RunnableConfig
 |             for more details.
 |
 |      Returns:
 |          The output of the Runnable.
 |
 |  prep_inputs(self, inputs: Union[Dict[str, Any], Any]) -> Dict[str, str]
 |      Prepare chain inputs, including adding inputs from memory.
 |
 |      Args:
 |          inputs: Dictionary of raw inputs, or single input if chain expects
 |              only one param. Should contain all inputs specified in
 |              `Chain.input_keys` except for inputs that will be set by the chain's
 |              memory.
 |
 |      Returns:
 |          A dictionary of all inputs, including those added by the chain's memory.
 |
 |  prep_outputs(self, inputs: Dict[str, str], outputs: Dict[str, str], return_only_outputs: bool = False) -> Dict[str, str]
 |      Validate and prepare chain outputs, and save info about this run to memory.
 |
 |      Args:
 |          inputs: Dictionary of chain inputs, including any inputs added by chain
 |              memory.
 |          outputs: Dictionary of initial chain outputs.
 |          return_only_outputs: Whether to only return the chain outputs. If False,
 |              inputs are also added to the final outputs.
 |
 |      Returns:
 |          A dict of the final chain outputs.
 |
 |  run(self, *args: Any, callbacks: Union[List[langchain_core.callbacks.base.BaseCallbackHandler], langchain_core.callbacks.base.BaseCallbackManager, NoneType] = None, tags: Optional[List[str]] = None, metadata: Optional[Dict[str, Any]] = None, **kwargs: Any) -> Any
 |      .. deprecated:: langchain==0.1.0 Use ``invoke`` instead.
 |
 |      Convenience method for executing chain.
 |
 |      The main difference between this method and `Chain.__call__` is that this
 |      method expects inputs to be passed directly in as positional arguments or
 |      keyword arguments, whereas `Chain.__call__` expects a single input dictionary
 |      with all the inputs
 |
 |      Args:
 |          *args: If the chain expects a single input, it can be passed in as the
 |              sole positional argument.
 |          callbacks: Callbacks to use for this chain run. These will be called in
 |              addition to callbacks passed to the chain during construction, but only
 |              these runtime callbacks will propagate to calls to other objects.
 |          tags: List of string tags to pass to all callbacks. These will be passed in
 |              addition to tags passed to the chain during construction, but only
 |              these runtime tags will propagate to calls to other objects.
 |          **kwargs: If the chain expects multiple inputs, they can be passed in
 |              directly as keyword arguments.
 |
 |      Returns:
 |          The chain output.
 |
 |      Example:
 |          .. code-block:: python
 |
 |              # Suppose we have a single-input chain that takes a 'question' string:
 |              chain.run("What's the temperature in Boise, Idaho?")
 |              # -> "The temperature in Boise is..."
 |
 |              # Suppose we have a multi-input chain that takes a 'question' string
 |              # and 'context' string:
 |              question = "What's the temperature in Boise, Idaho?"
 |              context = "Weather report for Boise, Idaho on 07/03/23..."
 |              chain.run(question=question, context=context)
 |              # -> "The temperature in Boise is..."
 |
 |  save(self, file_path: Union[pathlib.Path, str]) -> None
 |      Save the chain.
 |
 |      Expects `Chain._chain_type` property to be implemented and for memory to be
 |          null.
 |
 |      Args:
 |          file_path: Path to file to save the chain to.
 |
 |      Example:
 |          .. code-block:: python
 |
 |              chain.save(file_path="path/chain.yaml")
 |
 |  ----------------------------------------------------------------------
 |  Class methods inherited from langchain.chains.base.Chain:
 |
 |  raise_callback_manager_deprecation(values: Dict) -> Dict
 |      Raise deprecation warning if callback_manager is used.
 |
 |  set_verbose(verbose: Optional[bool]) -> bool
 |      Set the chain verbosity.
 |
 |      Defaults to the global setting if not specified by the user.
 |
 |  ----------------------------------------------------------------------
 |  Data and other attributes inherited from langchain.chains.base.Chain:
 |
 |  __orig_bases__ = (langchain_core.runnables.base.RunnableSerializab...t...
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from langchain_core.runnables.base.RunnableSerializable:
 |
 |  configurable_alternatives(self, which: 'ConfigurableField', *, default_key: 'str' = 'default', prefix_keys: 'bool' = False, **kwargs: 'Union[Runnable[Input, Output], Callable[[], Runnable[Input, Output]]]') -> 'RunnableSerializable[Input, Output]'
 |      Configure alternatives for Runnables that can be set at runtime.
 |
 |      Args:
 |          which: The ConfigurableField instance that will be used to select the
 |              alternative.
 |          default_key: The default key to use if no alternative is selected.
 |              Defaults to "default".
 |          prefix_keys: Whether to prefix the keys with the ConfigurableField id.
 |              Defaults to False.
 |          **kwargs: A dictionary of keys to Runnable instances or callables that
 |              return Runnable instances.
 |
 |      Returns:
 |          A new Runnable with the alternatives configured.
 |
 |      .. code-block:: python
 |
 |          from langchain_anthropic import ChatAnthropic
 |          from langchain_core.runnables.utils import ConfigurableField
 |          from langchain_openai import ChatOpenAI
 |
 |          model = ChatAnthropic(
 |              model_name="claude-3-sonnet-20240229"
 |          ).configurable_alternatives(
 |              ConfigurableField(id="llm"),
 |              default_key="anthropic",
 |              openai=ChatOpenAI()
 |          )
 |
 |          # uses the default model ChatAnthropic
 |          print(model.invoke("which organization created you?").content)
 |
 |          # uses ChatOpenAI
 |          print(
 |              model.with_config(
 |                  configurable={"llm": "openai"}
 |              ).invoke("which organization created you?").content
 |          )
 |
 |  configurable_fields(self, **kwargs: 'AnyConfigurableField') -> 'RunnableSerializable[Input, Output]'
 |      Configure particular Runnable fields at runtime.
 |
 |      Args:
 |          **kwargs: A dictionary of ConfigurableField instances to configure.
 |
 |      Returns:

In [82]:
# overall_chain: input= Review 
# and output= English_Review,summary, followup_message
overall_chain = SequentialChain(
    chains=[chain_one, chain_two, chain_three, chain_four],
    input_variables= ["Review"],
    output_variables=["espaReview", "sumR1", "GermanReview","stepback"],
    verbose=True
)

In [83]:
review = df.Review[5]
overall_chain(review)

Error in StdOutCallbackHandler.on_chain_start callback: AttributeError("'NoneType' object has no attribute 'get'")

> Finished chain.

{'Review': "Je trouve le goût médiocre. La mousse ne tient pas, c'est bizarre. J'achète les mêmes dans le commerce et le goût est bien meilleur...\nVieux lot ou contrefaçon !?",
 'espaReview': 'Encuentro el sabor mediocre. La espuma no se mantiene, es extraño. Compro los mismos en el comercio y el sabor es mucho mejor... ¿Lote viejo o falsificación!?',
 'sumR1': 'El sabor es mediocre y la espuma no se mantiene, comparado con los mismos comprados en el comercio.',
 'GermanReview': 'Ich finde den Geschmack mittelmäßig. Der Schaum hält nicht, das ist komisch. Ich kaufe die gleichen in Geschäften und der Geschmack ist viel besser... Alte Charge oder Fälschung!? \n\n(German)',
 'stepback': 'Both versions of the review mention that the taste is mediocre, but the German version also includes a comment about the foam not lasting, which is seen as strange. Additionally, the German version raises the concern of whether the product is an old batch or a counterfeit. The Spanish summary captures the main points of the German review, highlighting the mediocre taste and lack of foam retention when compared to similar products bought in stores. The analysis could have been more detailed, but it effectively conveys the main points of the original review.'}

**Repeat the above twice for different products or reviews**

## Router Chain

In [84]:
physics_template = """You are a very smart physics professor. \
You are great at answering questions about physics in a concise\
and easy to understand manner. \
When you don't know the answer to a question you admit\
that you don't know.

Here is a question:
{input}"""

math_template = """You are a very good mathematician. \
You are great at answering math questions. \
You are so good because you are able to break down \
hard problems into their component parts, 
answer the component parts, and then put them together\
to answer the broader question.

Here is a question:
{input}"""

history_template = """You are a very good historian. \
You have an excellent knowledge of and understanding of people,\
events and contexts from a range of historical periods. \
You have the ability to think, reflect, debate, discuss and \
evaluate the past. You have a respect for historical evidence\
and the ability to make use of it to support your explanations \
and judgements.

Here is a question:
{input}"""


computerscience_template = """ You are a successful computer scientist.\
You have a passion for creativity, collaboration,\
forward-thinking, confidence, strong problem-solving capabilities,\
understanding of theories and algorithms, and excellent communication \
skills. You are great at answering coding questions. \
You are so good because you know how to solve a problem by \
describing the solution in imperative steps \
that a machine can easily interpret and you know how to \
choose a solution that has a good balance between \
time complexity and space complexity. 

Here is a question:
{input}"""

biology_template = """You are an excellent biologist. \
You have a deep understanding of living organisms, \
from the molecular and cellular level to entire ecosystems. \
You are skilled at observing patterns in nature, analyzing biological data, \
and explaining complex processes like evolution, genetics, physiology, and ecology. \
You can clearly communicate how life functions and adapts, \
and you make connections between different biological concepts \
to answer challenging questions.

Here is a question:
{input}"""

In [85]:
prompt_infos = [
    {
        "name": "physics", 
        "description": "Good for answering questions about physics", 
        "prompt_template": physics_template
    },
    {
        "name": "math", 
        "description": "Good for answering math questions", 
        "prompt_template": math_template
    },
    {
        "name": "History", 
        "description": "Good for answering history questions", 
        "prompt_template": history_template
    },
    {
        "name": "computer science", 
        "description": "Good for answering computer science questions", 
        "prompt_template": computerscience_template
    },
    {
        "name": "biology",
        "description": "Good for answering biology questions",
        "prompt_template": biology_template
    }
]

In [86]:
from langchain.chains.router import MultiPromptChain
from langchain.chains.router.llm_router import LLMRouterChain,RouterOutputParser
from langchain.prompts import PromptTemplate

In [87]:
llm = ChatOpenAI(temperature=0)

In [88]:
destination_chains = {}
for p_info in prompt_infos:
    name = p_info["name"]
    prompt_template = p_info["prompt_template"]
    prompt = ChatPromptTemplate.from_template(template=prompt_template)
    chain = LLMChain(llm=llm, prompt=prompt)
    destination_chains[name] = chain  
    
destinations = [f"{p['name']}: {p['description']}" for p in prompt_infos]
destinations_str = "\n".join(destinations)

In [89]:
default_prompt = ChatPromptTemplate.from_template("{input}")
default_chain = LLMChain(llm=llm, prompt=default_prompt)

In [91]:
MULTI_PROMPT_ROUTER_TEMPLATE = """Given a raw text input to a \
language model select the model prompt best suited for the input. \
You will be given the names of the available prompts and a \
description of what the prompt is best suited for. \
You may also revise the original input if you think that revising\
it will ultimately lead to a better response from the language model.

<< FORMATTING >>
Return a markdown code snippet with a JSON object formatted to look like:
```json
{{{{
    "destination": string \ name of the prompt to use or "DEFAULT"
    "next_inputs": string \ a potentially modified version of the original input
}}}}
```

REMEMBER: "destination" MUST be one of the candidate prompt \
names specified below OR it can be "DEFAULT" if the input is not\
well suited for any of the candidate prompts.
REMEMBER: "next_inputs" can just be the original input \
if you don't think any modifications are needed.

<< CANDIDATE PROMPTS >>
{destinations}

<< INPUT >>
{{input}}

<< OUTPUT (remember to include the ```json)>>"""

In [92]:
router_template = MULTI_PROMPT_ROUTER_TEMPLATE.format(
    destinations=destinations_str
)
router_prompt = PromptTemplate(
    template=router_template,
    input_variables=["input"],
    output_parser=RouterOutputParser(),
)

router_chain = LLMRouterChain.from_llm(llm, router_prompt)

In [93]:
chain = MultiPromptChain(router_chain=router_chain, 
                         destination_chains=destination_chains, 
                         default_chain=default_chain, verbose=True
                        )

/var/folders/dk/w5mlpx9x4t9fj30jk64759lh0000gn/T/ipykernel_55678/3038952769.py:1: LangChainDeprecationWarning: Use RunnableLambda to select from multiple prompt templates. See example in API reference: https://api.python.langchain.com/en/latest/chains/langchain.chains.router.multi_prompt.MultiPromptChain.html
  chain = MultiPromptChain(router_chain=router_chain,

In [94]:
chain.run("What is black body radiation?")

Error in StdOutCallbackHandler.on_chain_start callback: AttributeError("'NoneType' object has no attribute 'get'")

physics: {'input': 'What is black body radiation?'}
> Finished chain.

"Black body radiation refers to the electromagnetic radiation emitted by a perfect black body, which is an idealized physical body that absorbs all incident electromagnetic radiation and emits radiation at all frequencies. The radiation emitted by a black body depends only on its temperature and follows a specific distribution known as Planck's law. This phenomenon is important in understanding the behavior of objects at high temperatures and is a key concept in the field of thermal physics."

In [95]:
chain.run("what is 2 + 2")

Error in StdOutCallbackHandler.on_chain_start callback: AttributeError("'NoneType' object has no attribute 'get'")

math: {'input': 'what is 2 + 2'}
> Finished chain.

'The answer to 2 + 2 is 4.'

In [96]:
chain.run("Why does every cell in our body contain DNA?")

Error in StdOutCallbackHandler.on_chain_start callback: AttributeError("'NoneType' object has no attribute 'get'")

biology: {'input': 'Why does every cell in our body contain DNA?'}
> Finished chain.

"Every cell in our body contains DNA because DNA is the genetic material that carries the instructions for the development, functioning, and reproduction of all living organisms. DNA contains the information needed to build and maintain an organism, including the proteins that make up our cells and tissues. \n\nHaving DNA in every cell ensures that each cell has the necessary genetic information to carry out its specific functions and to replicate itself accurately during cell division. This ensures that the genetic information is passed on to the next generation of cells, maintaining the integrity and continuity of the organism's genetic code.\n\nAdditionally, DNA serves as a storage system for genetic information, allowing for the transmission of traits from one generation to the next through the process of inheritance. This is essential for the survival and evolution of species, as it allows for genetic variation and adaptation to changing environments over time. \n\nIn summary, every cell in our body contains DNA because it is essential for the proper functioning, development, and reproduction of living organisms."

**Repeat the above at least once for different inputs and chains executions - Be creative!**

In [97]:
chain.run("Who was Atawalpa and wich country save his name as great lider?")

Error in StdOutCallbackHandler.on_chain_start callback: AttributeError("'NoneType' object has no attribute 'get'")

History: {'input': 'Who was Atawalpa and which country saw him as a great leader?'}
> Finished chain.

"Atawalpa was the last ruling Inca emperor of the Inca Empire in South America. He was the son of Inca Emperor Huayna Capac and became emperor after his father's death in 1525. Atawalpa was seen as a great leader by the people of the Inca Empire, which encompassed present-day Peru, Ecuador, Bolivia, and parts of Chile and Argentina. However, his reign was cut short by the Spanish conquistadors led by Francisco Pizarro, who captured and eventually executed Atawalpa in 1533."

In [103]:
chain.run("what is a multicystic person and what happen in their bodies?")

Error in StdOutCallbackHandler.on_chain_start callback: AttributeError("'NoneType' object has no attribute 'get'")

biology: {'input': 'what is a multicystic person and what happen in their bodies?'}
> Finished chain.

'A multicystic person is someone who has multiple cysts in their body. Cysts are fluid-filled sacs that can form in various tissues and organs. In the context of biology, multicystic usually refers to a medical condition where multiple cysts develop in a particular organ or system.\n\nFor example, a person with multicystic kidney disease may have numerous cysts in their kidneys, which can lead to kidney dysfunction and potentially kidney failure. Similarly, multicystic liver disease involves the formation of cysts in the liver, which can impair liver function and lead to complications.\n\nThe development of cysts in the body can be caused by a variety of factors, including genetic mutations, infections, inflammation, or other underlying health conditions. The presence of multiple cysts can disrupt the normal structure and function of the affected organ, leading to symptoms such as pain, swelling, organ dysfunction, and in severe cases, organ failure.\n\nTreatment for multicystic conditions typically involves managing symptoms, monitoring the growth of cysts, and in some cases, surgical intervention to remove cysts or affected organs. Genetic counseling may also be recommended for individuals with inherited forms of multicystic diseases.'

In [104]:
chain.run("what speed need an airplane to achieve 50.000km of altitude succesfully?")

Error in StdOutCallbackHandler.on_chain_start callback: AttributeError("'NoneType' object has no attribute 'get'")

physics: {'input': 'what speed does an airplane need to achieve 50,000 km of altitude successfully?'}
> Finished chain.

'To achieve an altitude of 50,000 km, an airplane would need to reach escape velocity, which is approximately 11.2 km/s (kilometers per second). This speed is necessary to overcome the gravitational pull of the Earth and reach outer space.'

In [105]:
chain.run("how many planets arethe cientifics discover in milkyway galaxy?")

Error in StdOutCallbackHandler.on_chain_start callback: AttributeError("'NoneType' object has no attribute 'get'")

None: {'input': 'how many planets arethe cientifics discover in milkyway galaxy?'}
> Finished chain.

'As of now, scientists have discovered over 4,000 exoplanets in the Milky Way galaxy.'